image: docker
services:
  - docker:dind

stages:
  - test
  
test:
  stage: test
  except:
    - schedules
  before_script:
    - apk add --no-cache curl
    - apk add --no-cache make
    - apk add --no-cache docker-compose
  
  script:
    - make test
  only:
    refs:
      - merge_requests
      - master
  
  artifacts:
    reports:
      cobertura: [coverage/cobertura-coverage.xml, coverage/cobertura-coverage.xml]