image: docker
services:
  - docker:dind

stages:
  - test
  - post-merge-tests
  
run-tests:  
  stage: test
  except:
    - schedules
  before_script:
    - apk add --no-cache curl
    - apk add --no-cache make
    - apk add --no-cache docker-compose
  script:
    - make test
  only:
    refs:
      - merge_requests
  
  artifacts:
    reports:
      cobertura: [coverage-unit/cobertura-coverage.xml, coverage-integration/cobertura-coverage.xml]
  
post-merge-tests:
  resource_group: 
  stage: post-merge-tests
  when: on_success

  artifacts:
    reports:
      cobertura: [coverage-unit/cobertura-coverage.xml, coverage-integration/cobertura-coverage.xml]